#include <iostream>

void MyWrappedFunction(void) {
   try { throw "In thrower"; }
   catch (const char * str) { cout<<"Exception"<< str << endl; }
}
